======================================================== test session starts ========================================================
platform win32 -- Python 3.9.13, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- C:\Users\j_mar\anaconda3\envs\mlflow-959bb272d47f76e4e40a52608a2bb126b2b20079\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\j_mar\Desktop\mlops-2022\tasks\project\check_data
collected 2 items
test_data.py::test_column_presence_and_type <class 'pandas.core.frame.DataFrame'>
FAILED
test_data.py::test_column_ranges FAILED
============================================================= FAILURES ==============================================================
___________________________________________________ test_column_presence_and_type ___________________________________________________
data =        host_listings_count  review_scores_rating neighbourhood_cleansed  ... number_of_reviews   latitude  longitude
0....0              4.620987            São Conrado  ...                 0 -22.994539 -43.258093
[24527 rows x 15 columns]
    def test_column_presence_and_type(data):
        print(type(data))
        # Disregard the reference dataset
        df = data
        required_columns = {
            "host_listings_count": pd.api.types.is_float_dtype,
            "review_scores_rating": pd.api.types.is_float_dtype,
            "neighbourhood_cleansed": pd.api.types.is_object_dtype,
            "property_type": pd.api.types.is_object_dtype,
>           "accommodates": pd.api.types.is_int_dtype,
            "room_type": pd.api.types.is_object_dtype,
            "bedrooms": pd.api.types.is_float_dtype,
            "beds": pd.api.types.is_float_dtype,
            "price": pd.api.types.is_float_dtype,
            "minimum_nights": pd.api.types.is_int_dtype,
            "bathrooms_text": pd.api.types.is_float_dtype,
            "maximum_nights": pd.api.types.is_int_dtype,
            "number_of_reviews": pd.api.types.is_int_dtype,
            "latitude": pd.api.types.is_float_dtype,
            "longitude": pd.api.types.is_float_dtype,
        }
E       AttributeError: module 'pandas.api.types' has no attribute 'is_int_dtype'
test_data.py:15: AttributeError
________________________________________________________ test_column_ranges _________________________________________________________
data =        host_listings_count  review_scores_rating neighbourhood_cleansed  ... number_of_reviews   latitude  longitude
0....0              4.620987            São Conrado  ...                 0 -22.994539 -43.258093
[24527 rows x 15 columns]
    def test_column_ranges(data):
        # Disregard the reference dataset
>       _, df = data
E       ValueError: too many values to unpack (expected 2)
test_data.py:39: ValueError
========================================================= warnings summary ==========================================================
..\..\..\..\..\anaconda3\envs\mlflow-959bb272d47f76e4e40a52608a2bb126b2b20079\lib\site-packages\win32\lib\pywintypes.py:2
  C:\Users\j_mar\anaconda3\envs\mlflow-959bb272d47f76e4e40a52608a2bb126b2b20079\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os
-- Docs: https://docs.pytest.org/en/stable/warnings.html
====================================================== short test summary info ======================================================
FAILED test_data.py::test_column_presence_and_type - AttributeError: module 'pandas.api.types' has no attribute 'is_int_dtype'
FAILED test_data.py::test_column_ranges - ValueError: too many values to unpack (expected 2)
=================================================== 2 failed, 1 warning in 7.52s ====================================================